-- begin AUTODEAL_COLOR
create unique index IDX_AUTODEAL_COLOR_UK_CODE on AUTODEAL_COLOR (CODE) where DELETE_TS is null ^
create unique index IDX_AUTODEAL_COLOR_UK_NAME on AUTODEAL_COLOR (NAME) where DELETE_TS is null ^
-- end AUTODEAL_COLOR
-- begin AUTODEAL_MANUFACTURER
alter table AUTODEAL_MANUFACTURER add constraint FK_AUTODEAL_MANUFACTURER_ON_COUNTRY foreign key (COUNTRY_ID) references AUTODEAL_COUNTRY(ID)^
create unique index IDX_AUTODEAL_MANUFACTURER_UK_CODE on AUTODEAL_MANUFACTURER (CODE) where DELETE_TS is null ^
create unique index IDX_AUTODEAL_MANUFACTURER_UK_NAME on AUTODEAL_MANUFACTURER (NAME) where DELETE_TS is null ^
create index IDX_AUTODEAL_MANUFACTURER_ON_COUNTRY on AUTODEAL_MANUFACTURER (COUNTRY_ID)^
-- end AUTODEAL_MANUFACTURER
-- begin AUTODEAL_BUY_REQUEST
alter table AUTODEAL_BUY_REQUEST add constraint FK_AUTODEAL_BUY_REQUEST_ON_AUTO foreign key (AUTO_ID) references AUTODEAL_AUTO(ID)^
alter table AUTODEAL_BUY_REQUEST add constraint FK_AUTODEAL_BUY_REQUEST_ON_CLIENT foreign key (CLIENT_ID) references AUTODEAL_CLIENT(ID)^
alter table AUTODEAL_BUY_REQUEST add constraint FK_AUTODEAL_BUY_REQUEST_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
create index IDX_AUTODEAL_BUY_REQUEST_ON_AUTO on AUTODEAL_BUY_REQUEST (AUTO_ID)^
create index IDX_AUTODEAL_BUY_REQUEST_ON_CLIENT on AUTODEAL_BUY_REQUEST (CLIENT_ID)^
create index IDX_AUTODEAL_BUY_REQUEST_ON_MANAGER on AUTODEAL_BUY_REQUEST (MANAGER_ID)^
-- end AUTODEAL_BUY_REQUEST
-- begin AUTODEAL_AUTO
alter table AUTODEAL_AUTO add constraint FK_AUTODEAL_AUTO_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references AUTODEAL_MANUFACTURER(ID)^
alter table AUTODEAL_AUTO add constraint FK_AUTODEAL_AUTO_ON_MODEL foreign key (MODEL_ID) references AUTODEAL_MODEL(ID)^
alter table AUTODEAL_AUTO add constraint FK_AUTODEAL_AUTO_ON_COMPLECTATION foreign key (COMPLECTATION_ID) references AUTODEAL_COMPLECTATION(ID)^
create index IDX_AUTODEAL_AUTO_ON_MANUFACTURER on AUTODEAL_AUTO (MANUFACTURER_ID)^
create index IDX_AUTODEAL_AUTO_ON_MODEL on AUTODEAL_AUTO (MODEL_ID)^
create index IDX_AUTODEAL_AUTO_ON_COMPLECTATION on AUTODEAL_AUTO (COMPLECTATION_ID)^
-- end AUTODEAL_AUTO
-- begin AUTODEAL_MODEL
alter table AUTODEAL_MODEL add constraint FK_AUTODEAL_MODEL_ON_MANUFACTURER foreign key (MANUFACTURER_ID) references AUTODEAL_MANUFACTURER(ID)^
alter table AUTODEAL_MODEL add constraint FK_AUTODEAL_MODEL_ON_COMPLECTATION foreign key (COMPLECTATION_ID) references AUTODEAL_COMPLECTATION(ID)^
create index IDX_AUTODEAL_MODEL_ON_MANUFACTURER on AUTODEAL_MODEL (MANUFACTURER_ID)^
create index IDX_AUTODEAL_MODEL_ON_COMPLECTATION on AUTODEAL_MODEL (COMPLECTATION_ID)^
-- end AUTODEAL_MODEL
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_COUNTRY foreign key (COUNTRY_ID) references AUTODEAL_COUNTRY(ID)^
create index IDX_SEC_USER_ON_COUNTRY on SEC_USER (COUNTRY_ID)^
-- end SEC_USER
